alias config="vim ~/.dotfiles/home-fs/.config/i3/config"
alias dot="cd ~/.dotfiles"
alias aliases="vim ~/.dotfiles/home-fs/.aliases.sh"
alias barconfig="vim ~/.dotfiles/home-fs/.i3status.conf"
alias outlook="firefox --new-window  https://outlook.office365.com/mail &"
alias teams="firefox --new-window  https://teams.microsoft.com/v2/ &"
alias tumblr="firefox --new-window  https://www.tumblr.com &"
alias fencing="firefox --new-window --profile "$(realpath $HOME/.mozilla/firefox/*\.Drexel\ Fencing | sed -e 's/ /\\ /')" & " #uses profile specific to Joe desktop, dont use
alias keychron="chromium 'https://launcher.keychron.com' &"
