#!bin/bash

alias outlook="firefox --new-window  https://outlook.office365.com/mail &"
alias teams="chromium --app=https://teams.microsoft.com &"
alias onedrive="chromium --new-window https://teams.microsoft.com/v2/ &"
alias tumblr="firefox --new-window  https://www.tumblr.com &"
alias fencing="firefox --new-window -P \"Drexel Fencing\""
alias hemail="firefox --new-window -P \"hechts\" https://outlook.office365.com/mail"
alias keychron="chromium 'https://launcher.keychron.com' &"
alias slack="flatpak run com.slack.Slack &"
alias spotify="flatpak run com.spotify.Client"
alias pinta="flatpak run com.github.PintaProject.Pinta &"
alias files="nautilus &"
alias videos="totem &"
alias video="totem"
alias shop="gnome-software &"
alias chirp="~/.local/bin/chirp"
alias drexelvpn="gtk-launch com.cisco.secureclient.gui"

alias discord="flatpak run com.discordapp.Discord &"
alias prusaslicer="flatpak run com.prusa3d.PrusaSlicer &"
alias rpi="flatpak run org.raspberrypi.rpi-imager &"
alias whatsapp="flatpak run com.rtosta.zapzap"
alias wa="flatpak run com.rtosta.zapzap"
alias logisim="flatpak run com.github.reds.LogisimEvolution"

alias gradescope="firefox https://www.gradescope.com/ &"
alias overleaf="firefox https://www.overleaf.com/project &"
alias github="firefox https://github.com/Joel-Hecht/.dotfiles &"
alias clanker="firefox https://claude.ai &"
