#source .bashrc instead of .bash_profile
set-option -g default-command bash

#set default prefix key to ctrl a instead of ctrl b because I do not like it
unbind C-b
set -g prefix C-a
bind C-a send-prefix
