all:
	scripts/makealiases.sh
	scripts/makebfsaliases.py
	scripts/makenitrogenconfig.sh
	scripts/makesymlinks.sh
	scripts/permission_setup.sh
	scripts/makemans.sh

sym:
	scripts/makesymlinks.sh

mans:
	scripts/makemans.sh
