all:
	scripts/make_aliases.sh
	scripts/make_bfs_aliases.py
	scripts/make_nitrogen_config.sh
	scripts/make_symlinks.sh
	scripts/permission_setup.sh

sym:
	scripts/make_symlinks.sh

font:
	scripts/font_setup.sh
