font_family		 monospace
bold_font        monospace
italic_font      auto
bold_italic_font auto
font_size 14.0
inactive_text_alpha 0.8
hide_window_decorations yes
window_padding_width 5 
touch_scroll_multiplier -1
background_opacity 0.68

enable_audio_bell no

# BEGIN_KITTY_THEME
# Harper
include current-theme.conf
# END_KITTY_THEME

# cool animations
# cursor_shape beam
# cursor_trail 1

#open a new terminal to the current location
map kitty_mod+' new_os_window_with_cwd 

#change shortcut for scrollback buffer so i can use it in nvim
map ctrl+shift+h
map ctrl+shift+m show_scrollback

#change shortcut to move to next layout so I can use it in nvim
map ctrl+shift+l
map ctrl+shift+y next_layout

#I need kitty to send a null byte to trigger nvim blink autocomplete
map ctrl+space send_text all \x00
