font_family		 monospace
bold_font        monospace
italic_font      auto
bold_italic_font auto
font_size 14.0
background_opacity 0.68
inactive_text_alpha 0.5
hide_window_decorations yes
window_padding_width 5 

enable_audio_bell no

# BEGIN_KITTY_THEME
# Harper
include current-theme.conf
# END_KITTY_THEME

# cool animations
cursor_shape beam
cursor_trail 1
