protocol file
fragment_matches [0-9]+
action launch --type=overlay --cwd=current vim +$FRAGMENT -- ${FILE_PATH}

protocol file
mime text/*
action launch --type=overlay --cwd=current vim -- ${FILE_PATH}

protocol file
mime image/*
action launch --type=overlay --cwd=current eog $FILE_PATH

protocol filelist
action send_text all ${FRAGMENT}
